apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ial2xmb2k-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-eee46d8e79.cdja.p3.openshiftapps.com/rhtap/rhtap-qe:16509d44c547f2fe852e5dfa8795181310ffcd2d@sha256:bf2ce5c548cdf7d76f571b86803f0cc21bb821fdfa16ae280ee1eb854a94b588
          name: container-image
